from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import or_
from . import models, schemas
from .database import get_db
from .agents import curriculum, mentor, matching
from .agents.curriculum import CurriculumAgentError
from .agents.mentor import MentorAgentError
from .auth import get_current_user
from datetime import datetime, timezone
import hashlib
from typing import List

router = APIRouter()


# ─── Helper: Create Notification ─────────────────────────
def _create_notification(db: Session, user_id: int, text: str, notif_type: str = "info"):
    """Create a real notification record for a user."""
    notif = models.Notification(
        user_id=user_id,
        text=text,
        type=notif_type,
        unread=True,
        created_at=datetime.now(timezone.utc),
    )
    db.add(notif)


@router.post("/assess", response_model=schemas.LearningPathResponse)
def create_assessment(
    req: schemas.AssessmentRequest,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Re-assess and regenerate the user's learning roadmap."""
    try:
        roadmap_data = curriculum.generate_roadmap(req.goal, req.challenges)
    except CurriculumAgentError as e:
        raise HTTPException(status_code=503, detail=str(e))

    # Check if learning path exists
    existing = db.query(models.LearningPath).filter(
        models.LearningPath.user_id == current_user.id
    ).first()

    if existing:
        existing.primary_goal = roadmap_data.get("primary_goal", req.goal)
        existing.identified_gaps = roadmap_data.get("identified_gaps", "[]")
        existing.dependent_goal = roadmap_data.get("dependent_goal", "")
        existing.interested_goal = roadmap_data.get("interested_goal", "")
        existing.involved_goal = roadmap_data.get("involved_goal", "")
        existing.self_directed_goal = roadmap_data.get("self_directed_goal", "")
        _create_notification(db, current_user.id, "Your learning roadmap has been regenerated by the Curriculum Agent.", "info")
        db.commit()
        db.refresh(existing)
        return existing
    else:
        learning_path = models.LearningPath(
            user_id=current_user.id,
            primary_goal=roadmap_data.get("primary_goal", req.goal),
            identified_gaps=roadmap_data.get("identified_gaps", "[]"),
            dependent_goal=roadmap_data.get("dependent_goal", ""),
            interested_goal=roadmap_data.get("interested_goal", ""),
            involved_goal=roadmap_data.get("involved_goal", ""),
            self_directed_goal=roadmap_data.get("self_directed_goal", ""),
        )
        db.add(learning_path)
        _create_notification(db, current_user.id, "Your personalized learning roadmap has been created!", "success")
        db.commit()
        db.refresh(learning_path)
        return learning_path


@router.post("/artifacts", response_model=schemas.ArtifactResponse)
def submit_artifact(
    artifact: schemas.ArtifactCreate,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Submit an artifact for Mentor Agent evaluation."""
    try:
        evaluation = mentor.evaluate_artifact(
            artifact.content, artifact.type, str(current_user.current_stage)
        )
    except MentorAgentError as e:
        raise HTTPException(status_code=503, detail=str(e))

    new_artifact = models.Artifact(
        user_id=current_user.id,
        title=artifact.title,
        type=artifact.type,
        content=artifact.content,
        status=evaluation.get("status", "pending"),
        feedback=evaluation.get("feedback", ""),
        date_submitted=artifact.date_submitted or datetime.now().strftime("%Y-%m-%d"),
    )

    db.add(new_artifact)

    # Create notification for artifact feedback
    if new_artifact.status == "verified":
        _create_notification(
            db, current_user.id,
            f'Your artifact "{artifact.title}" has been verified by the Mentor Agent!',
            "success"
        )
    elif new_artifact.status == "rejected":
        _create_notification(
            db, current_user.id,
            f'Your artifact "{artifact.title}" needs revision. Check the Mentor feedback.',
            "warning"
        )

    # Stage progression logic
    if new_artifact.status == "verified":
        verified_count = (
            db.query(models.Artifact)
            .filter(
                models.Artifact.user_id == current_user.id,
                models.Artifact.status == "verified",
            )
            .count()
        )
        old_stage = current_user.current_stage
        # Advance stage after verified artifacts threshold
        if current_user.current_stage == models.StageEnum.dependent and verified_count >= 1:
            current_user.current_stage = models.StageEnum.interested
        elif current_user.current_stage == models.StageEnum.interested and verified_count >= 3:
            current_user.current_stage = models.StageEnum.involved
        elif current_user.current_stage == models.StageEnum.involved and verified_count >= 5:
            current_user.current_stage = models.StageEnum.self_directed

        if current_user.current_stage != old_stage:
            _create_notification(
                db, current_user.id,
                f"Congratulations! You've advanced to the {current_user.current_stage.value} stage!",
                "stage_advance"
            )

    db.commit()
    db.refresh(new_artifact)
    return new_artifact


@router.post("/match")
def trigger_matching(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Run the Gale-Shapley matching algorithm for accountability partners."""
    users = db.query(models.User).filter(models.User.onboarding_complete == True).all()

    if len(users) < 2:
        return {
            "message": "Not enough users for matching. At least 2 onboarded users are required.",
            "matches": 0,
        }

    # Build enriched user dicts with survey data for better matching
    user_dicts = []
    for u in users:
        user_dict = {
            "id": u.id,
            "major": u.major,
            "career_interest": u.career_interest,
            "current_stage": u.current_stage.value if u.current_stage else None,
        }
        # Include survey data if available
        if u.matching_survey:
            user_dict["learning_style"] = u.matching_survey.learning_style
            user_dict["preferred_schedule"] = u.matching_survey.preferred_schedule
        user_dicts.append(user_dict)

    matches = matching.gale_shapley_match(user_dicts)

    created_matches = []
    for m in matches:
        partner1, partner2, score = m
        existing = (
            db.query(models.PartnerMatch)
            .filter(
                (
                    (models.PartnerMatch.user1_id == partner1)
                    & (models.PartnerMatch.user2_id == partner2)
                )
                | (
                    (models.PartnerMatch.user1_id == partner2)
                    & (models.PartnerMatch.user2_id == partner1)
                )
            )
            .first()
        )

        # Generate a deterministic unique room ID for this pair
        pair_key = f"nexus-{min(partner1, partner2)}-{max(partner1, partner2)}"
        room_id = hashlib.sha256(pair_key.encode()).hexdigest()[:12]

        if not existing:
            new_match = models.PartnerMatch(
                user1_id=partner1,
                user2_id=partner2,
                match_score=score,
                next_meeting="Pending Schedule",
                room_id=room_id,
            )
            db.add(new_match)
            created_matches.append({"user1": partner1, "user2": partner2, "score": score})

            # Notify both partners
            p1 = db.query(models.User).filter(models.User.id == partner1).first()
            p2 = db.query(models.User).filter(models.User.id == partner2).first()
            if p1 and p2:
                _create_notification(
                    db, partner1,
                    f"You've been matched with {p2.name} as your accountability partner! ({score}% compatibility)",
                    "partner"
                )
                _create_notification(
                    db, partner2,
                    f"You've been matched with {p1.name} as your accountability partner! ({score}% compatibility)",
                    "partner"
                )

    db.commit()
    return {
        "message": f"Successfully created {len(created_matches)} new pairings.",
        "matches": created_matches,
    }


@router.get("/my-partner")
def get_my_partner(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Get current user's accountability partner."""
    match = (
        db.query(models.PartnerMatch)
        .filter(
            (models.PartnerMatch.user1_id == current_user.id)
            | (models.PartnerMatch.user2_id == current_user.id)
        )
        .first()
    )

    if not match:
        return {"partner": None, "message": "No partner match found. Run the matching algorithm."}

    partner_id = match.user2_id if match.user1_id == current_user.id else match.user1_id
    partner = db.query(models.User).filter(models.User.id == partner_id).first()

    return {
        "partner": {
            "id": partner.id,
            "name": partner.name,
            "major": partner.major or "Not set",
            "career_interest": partner.career_interest or "Not set",
            "current_stage": partner.current_stage.value if partner.current_stage else "Dependent",
            "score": match.match_score,
            "next_meeting": match.next_meeting,
            "room_id": match.room_id or "nexus-default",
        }
    }


# ─── Notifications ────────────────────────────────────────

@router.get("/notifications", response_model=List[schemas.NotificationResponse])
def get_notifications(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Get all notifications for the current user, ordered by most recent."""
    return (
        db.query(models.Notification)
        .filter(models.Notification.user_id == current_user.id)
        .order_by(models.Notification.created_at.desc())
        .limit(50)
        .all()
    )


@router.post("/notifications/read-all")
def mark_all_notifications_read(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Mark all notifications as read for the current user."""
    db.query(models.Notification).filter(
        models.Notification.user_id == current_user.id,
        models.Notification.unread == True,
    ).update({"unread": False})
    db.commit()
    return {"message": "All notifications marked as read."}


@router.post("/notifications/{notification_id}/read")
def mark_notification_read(
    notification_id: int,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Mark a single notification as read."""
    notif = db.query(models.Notification).filter(
        models.Notification.id == notification_id,
        models.Notification.user_id == current_user.id,
    ).first()
    if not notif:
        raise HTTPException(status_code=404, detail="Notification not found")
    notif.unread = False
    db.commit()
    return {"message": "Notification marked as read."}


# ─── Search ───────────────────────────────────────────────

@router.get("/search")
def search(
    q: str,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Search across artifacts, learning paths, and peers for the current user."""
    query = q.strip().lower()
    if not query:
        return {"artifacts": [], "learning_path_matches": [], "peers": []}

    search_pattern = f"%{query}%"

    # Search user's artifacts by title or content
    artifacts = (
        db.query(models.Artifact)
        .filter(
            models.Artifact.user_id == current_user.id,
            or_(
                models.Artifact.title.ilike(search_pattern),
                models.Artifact.content.ilike(search_pattern),
                models.Artifact.feedback.ilike(search_pattern),
            ),
        )
        .limit(10)
        .all()
    )

    # Search learning path goals
    lp_matches = []
    if current_user.learning_path:
        lp = current_user.learning_path
        for field_name, label in [
            ("primary_goal", "Primary Goal"),
            ("dependent_goal", "Dependent Stage"),
            ("interested_goal", "Interested Stage"),
            ("involved_goal", "Involved Stage"),
            ("self_directed_goal", "Self-Directed Stage"),
        ]:
            value = getattr(lp, field_name, "") or ""
            if query in value.lower():
                lp_matches.append({"field": label, "content": value})

    # Search peers (non-private users only) by name, major, or career interest
    peers = (
        db.query(models.User)
        .filter(
            models.User.id != current_user.id,
            models.User.onboarding_complete == True,
            models.User.pref_privacy == False,
            or_(
                models.User.name.ilike(search_pattern),
                models.User.major.ilike(search_pattern),
                models.User.career_interest.ilike(search_pattern),
            ),
        )
        .limit(10)
        .all()
    )

    return {
        "artifacts": [
            {
                "id": a.id,
                "title": a.title,
                "type": a.type,
                "status": a.status,
                "date_submitted": a.date_submitted,
            }
            for a in artifacts
        ],
        "learning_path_matches": lp_matches,
        "peers": [
            {
                "id": p.id,
                "name": p.name,
                "major": p.major,
                "career_interest": p.career_interest,
            }
            for p in peers
        ],
    }


# ─── User Preferences ────────────────────────────────────

@router.put("/preferences")
def update_preferences(
    prefs: schemas.UserPreferencesUpdate,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    """Update user preferences (dark mode, notifications, privacy)."""
    if prefs.pref_dark_mode is not None:
        current_user.pref_dark_mode = prefs.pref_dark_mode
    if prefs.pref_notifications is not None:
        current_user.pref_notifications = prefs.pref_notifications
    if prefs.pref_privacy is not None:
        current_user.pref_privacy = prefs.pref_privacy
    db.commit()
    db.refresh(current_user)
    return {
        "pref_dark_mode": current_user.pref_dark_mode,
        "pref_notifications": current_user.pref_notifications,
        "pref_privacy": current_user.pref_privacy,
    }
